---
- hosts: webservers
  vars:
    ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/id_rsa
    ansible_user: jenkins
    ansible_become: yes
  tasks:
    - name: Make sure that we can connect to the machine
      ping:

    - name: add group "tomcat"
      group: name=tomcat

    - name: add user "tomcat"
      user: name=tomcat group=tomcat createhome=yes
      become: true

    - name: copy Tomcat
      copy: src=./apache-tomcat-8.5.16.tar.gz dest=/opt/apache-tomcat-8.5.16.tar.gz

    - name: Extract Tomcat archive
      command: tar zxvf /opt/apache-tomcat-8.5.16.tar.gz -C /opt/ creates=/opt/apache-tomcat-8.5.16

    - name: Change ownership of Tomcat installation
      file: path=/opt/apache-tomcat-8.5.16 owner=tomcat group=tomcat state=directory recurse=yes

    - name: Configure Tomcat server
      template: src=server.xml dest=/opt/apache-tomcat-8.5.16/conf/

    - name: Configure Tomcat users
      template: src=tomcat-users.xml dest=/opt/apache-tomcat-8.5.16/conf/

    - name: Start Tomcat
      command: nohup /opt/apache-tomcat-8.5.16/bin/startup.sh
      become: true
      become_user: ansible

    - name: wait for tomcat to start
      wait_for: port={{http_port}}
